// ----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Sun Dec 16 14:43:24 PST 2007
//----------------------------------------------------

package compling.simulator;

/** CUP generated class containing symbol constants. */
public class ScriptReaderSym {
	/* terminals */
	public static final int EXEC = 2;
	public static final int CLOSEPAREN = 12;
	public static final int SEMICOLON = 8;
	public static final int OPENPAREN = 11;
	public static final int TEST = 3;
	public static final int REM = 22;
	public static final int TESTEXIST = 4;
	public static final int IDENTIFIER = 14;
	public static final int VARIABLE = 15;
	public static final int INST = 20;
	public static final int IND = 18;
	public static final int QUERYVAR = 16;
	public static final int EOF = 0;
	public static final int RUN = 7;
	public static final int error = 1;
	public static final int CURRENTINTERVAL = 21;
	public static final int CLOSEBRACKET = 10;
	public static final int OPENBRACKET = 9;
	public static final int STR = 17;
	public static final int NEGATION = 13;
	public static final int QUERY = 5;
	public static final int DEFAULT = 6;
	public static final int FIL = 19;
}
