// ----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Mon Sep 03 00:36:46 PDT 2007
//----------------------------------------------------

package compling.simulator;

/** CUP generated class containing symbol constants. */
public class ScriptSplitterSym {
	/* terminals */
	public static final int CONTENT = 4;
	public static final int SCRIPT = 2;
	public static final int error = 1;
	public static final int IDENTIFIER = 3;
	public static final int EOF = 0;
}
