
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Wed Mar 25 11:22:14 PDT 2015
//----------------------------------------------------

package compling.context;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IMPORT = 19;
  public static final int CLOSEPAREN = 3;
  public static final int OPENPAREN = 2;
  public static final int REM = 17;
  public static final int REL = 5;
  public static final int IDENTIFIER = 20;
  public static final int DEFS = 12;
  public static final int INSTS = 13;
  public static final int SUB = 4;
  public static final int IND = 7;
  public static final int INST = 15;
  public static final int TYPE = 14;
  public static final int EOF = 0;
  public static final int NONBLOCKING = 11;
  public static final int error = 1;
  public static final int CURRENTINTERVAL = 16;
  public static final int STR = 21;
  public static final int EQ = 9;
  public static final int PACKAGE = 18;
  public static final int FIL = 8;
  public static final int PERSISTENT = 10;
  public static final int FUN = 6;
}

