
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Fri May 18 17:19:05 PDT 2012
//----------------------------------------------------

package compling.grammar.ecg.ecgreader;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAP = 28;
  public static final int CONSTITUENTS = 23;
  public static final int SCHEMA = 5;
  public static final int ROLES = 22;
  public static final int EXTERNALTYPE = 32;
  public static final int IDENTIFIER = 30;
  public static final int IDENTIFY = 18;
  public static final int IGNORE = 27;
  public static final int AS = 20;
  public static final int CONSTRUCTION = 2;
  public static final int COLON = 11;
  public static final int OF = 21;
  public static final int SUBCASE = 3;
  public static final int FORM = 7;
  public static final int CONSTRUCTIONAL = 4;
  public static final int SITUATION = 29;
  public static final int CONSTRAINTS = 24;
  public static final int COMMA = 12;
  public static final int EOF = 0;
  public static final int BEFORE = 9;
  public static final int EXTRAPOSED = 16;
  public static final int SLOTCHAIN = 34;
  public static final int error = 1;
  public static final int CLOSEBRACKET = 14;
  public static final int OPENBRACKET = 13;
  public static final int PROB = 33;
  public static final int STR = 31;
  public static final int ASSIGN = 17;
  public static final int ABSTRACT = 6;
  public static final int MEETS = 10;
  public static final int EVOKES = 19;
  public static final int FEATURE = 25;
  public static final int SEMANTIC = 26;
  public static final int OPTIONAL = 15;
  public static final int MEANING = 8;
}

