
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Tue Jan 20 10:02:43 PST 2015
//----------------------------------------------------

package compling.grammar.ecg.ecgreader;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONSTITUENTS = 25;
  public static final int FORM = 9;
  public static final int MAP = 30;
  public static final int STR = 33;
  public static final int FEATURE = 27;
  public static final int OPTIONAL = 17;
  public static final int EXTERNALTYPE = 34;
  public static final int SUBCASE = 3;
  public static final int BEFORE = 11;
  public static final int SCHEMA = 5;
  public static final int MEANING = 10;
  public static final int SEMANTIC = 28;
  public static final int COMMA = 14;
  public static final int IDENTIFY = 20;
  public static final int EVOKES = 21;
  public static final int ASSIGN = 19;
  public static final int CONSTRUCTIONAL = 4;
  public static final int OF = 23;
  public static final int ABSTRACT = 6;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int CLOSEBRACKET = 16;
  public static final int IGNORE = 29;
  public static final int IMPORT = 8;
  public static final int COLON = 13;
  public static final int OPENBRACKET = 15;
  public static final int PACKAGE = 7;
  public static final int CONSTRAINTS = 26;
  public static final int SITUATION = 31;
  public static final int ROLES = 24;
  public static final int EXTRAPOSED = 18;
  public static final int PROB = 35;
  public static final int SLOTCHAIN = 36;
  public static final int CONSTRUCTION = 2;
  public static final int AS = 22;
  public static final int MEETS = 12;
  public static final int IDENTIFIER = 32;
}

